### ISSUE TITLE
rewrite the build/configuration system using autotools

### ISSUE THREAD

**Issue by mcol** [gchen98/mendel-gpu#1]
The build system should be using autotools to simplify building the code on different systems and checking for the required dependencies.

**Comment by gchen98** [comment]
I agree. I never got around to doing that.

**Comment by mcol** [comment]
I have a working version of this: I've tested it on two different systems, and it's ok. It still needs a bit of manual input, but the infrastructure is all in place. If you are happy with testing it out too, I'll go ahead and commit it, then take it from there.

**Comment by gchen98** [comment]
Sounds great. Check that in and I'll take a look! Thanks

**Comment by mcol** [comment]
I pushed the changes as 4a2bc7733fc6b3537837be24850d4270c7cf94ad and 36d5b384197f10aa7b636b694b78a2ce8b415697.

To create a build you first need to run:

```
autoreconf -fvi
./configure --with-samtools=<path>
```

On Ubuntu, with the libbam-dev package installed, <path> is /usr. If the OpenCL headers and library are not in the standard paths, you'll need to change the call to configure to the following: 

```
./configure --with-samtools=<path> CPPFLAGS="-I <path to headers>" LDFLAGS="-L <path to library>" 
```

**Comment by gchen98** [comment]
Hey Marco I tried it out and it seems to work so far so good. But however I tested it on a machine without a GPU or OpenCL.  Can this be set up so that OpenCL is optional? That is how I had it in include.mk with the D_USE_GPU flag.

**Comment by mcol** [comment]
At the moment that flag is hardcoded in Makefile.am, and it's assumed that OpenCL is available. I'll change it now to allow a build without it.

**Comment by mcol** [comment]
I've pushed 4a72828f058f7b57378c0a9e17c1a03c11929037 to allow building without OpenCL. Let me know how it works for you.

**Comment by gchen98** [comment]
Works great. Thanks for pushing this in.
