### ISSUE TITLE
lots of debugging output also if tuning_parameters.debug=0

### ISSUE THREAD

**Issue by mcol** [gchen98/mendel-gpu#10]
It seems that this option is not always considered. In particular, the very long series of messages

```
Will impute position 16052463
Will impute position 16052684
Will impute position 16053238
...
```

shouldn't happen with debug=0.

**Comment by gchen98** [comment]
Yes, this really ought to be classified as a debugging message.

**Comment by mcol** [comment]
Ok, this was fixed by c8b4a8154794262cfc3d71d7c7183bc776b3f4af.

**Comment by mcol** [comment]
I've committed another change in 05257a210ddb24fd4c1d2e972418e532e8987947. I'm reopening as there are more places that need this sort of work.

**Comment by gchen98** [comment]
Since commenting out some of these debugging messages is not going to affect the functionality of the program, please feel free to continue quieting down the output or increasing verbosity as you see fit. I'll close this one out, and just make edits as you see fit.
