### ISSUE TITLE
code stops abruptly when the environment variable IMPUTATION_SOFWARE is missing

### ISSUE THREAD

**Issue by mcol** [gchen98/mendel-gpu#2]
As this was not documented, I could not run the plink example to completion. Is there any reason why this is not part of settings.xml? Either way, the code should handle gracefully the lack of this variable.

**Comment by gchen98** [comment]
Yeah we should put error checking to ensure environment variables are 
set. Note that this was an environment variable in the earlier version 
of mendel-gpu where we had a set of scripts the did preprocessing. But 
we would like to do away with these external scripts and unify the 
functionality. Hence we should migrate the use of environment variables 
into settings.xml.

**Comment by mcol** [comment]
I agree with this. I'll first do the error check, as it's easy enough.

**Comment by mcol** [comment]
Fixed by 802afb6e2a0d339251795cbc56484ddf1eee6236. I've opened #4 to address the proper fix.
