### ISSUE TITLE
bam example fails

### ISSUE THREAD

**Issue by mcol** [gchen98/mendel-gpu#3]
Running the example in the bam directory fails with this message:

`Caught an exception attempting to parse XML: No such node (tuning_parameters.total_best_haps)`

Adding that node to the settings.xml file fixes the issue. For the future, wouldn't it be better to have a set of defaults to fall back on if some configuration setting is missing?

**Comment by gchen98** [comment]
Absolutely. But that is odd, I don't recall coming across this when checking in. Regardless, users are likely to have older versions of config files, and we should always provide a warning when a "new" key is missing, and notify what the default is.

**Comment by mcol** [comment]
I've added the missing setting in 4b6a0d4280d537ee10821441b3c88eacb507520c.
