### ISSUE TITLE
move IMPUTATION_SOFWARE into settings.xml

### ISSUE THREAD

**Issue by mcol** [gchen98/mendel-gpu#4]
This would be a better way of setting it, rather than relying on an environmental variable. See issue #2.

**Comment by gchen98** [comment]
Since this is really an offshoot of #2 we'll close this out.

**Comment by mcol** [comment]
I created this to keep track of something that needs to be sorted out, so it's a bit early to close it. Issue #2 was just the quick hack to at least get an informative message.
