### ISSUE TITLE
obscure error if the phased_input option is not provided

### ISSUE THREAD

**Issue by mcol** [gchen98/mendel-gpu#8]
When using the glf program, the phased_input option must be set to 0 or 1. If it's left blank, the following message is reported:

```
Caught an exception attempting to parse XML: conversion of data to type "b" failed
Caught an exception with message Cannot load configuration file
```

I'm not sure how to fix this properly. The easiest thing is to set a default value of 0, like this:

```
config->is_phased = pt.get<bool>("glf_settings.phased_input", 0)
```

However, I don't know how to warn the user that a default value is being used.

**Comment by mcol** [comment]
Of course the same message happens if any other boolean field is left blank, such as use_gpu.

**Comment by gchen98** [comment]
I think your idea of using a default is reasonable and should be robust. Can you do a full dump of all current parameters? At least the user will know before program output is generated that they entered all the parameters correctly.

**Comment by mcol** [comment]
That would be the sensible approach, but it's not a priority for us now.

**Comment by mcol** [comment]
In the meantime I've set some default values in a9fbff79dc17d4864de2658745984ea9b162c257.
